//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _422_Dubkova_UP_Ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class ads_data
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string ad_title { get; set; }
        public string ad_description { get; set; }
        public System.DateTime ad_post_date { get; set; }
        public int city_id { get; set; }
        public int category { get; set; }
        public int ad_type_id { get; set; }
        public int ad_status_id { get; set; }
        public decimal price { get; set; }
        public string ad_image_path { get; set; }
    
        public virtual status status { get; set; }
        public virtual type type { get; set; }
        public virtual category category1 { get; set; }
        public virtual city city { get; set; }
        public virtual user user { get; set; }
    }
}
