//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _422_Dubkova_UP_Ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class profit
    {
        public int user_id { get; set; }
        public Nullable<decimal> profit1 { get; set; }
    
        public virtual user user { get; set; }
    }
}
